### ISSUE TITLE
Release Checklist

### ISSUE THREAD

**Issue by jameslkingsley** [marseditor/mars#27]
- [ ] Spawning
  - [ ] Works on all session types (multiplayer, singleplayer)
  - [ ] Objects get created as expected (no random deaths, glitches)
- [ ] UI
  - [ ] Context menus pass correct arguments to options expression
  - [ ] Menustrip doesn't crash game when using `call` on dialog code
  - [ ] Toolbar doesn't crash game when using `call` on dialog code
  - [ ] Attributes load and pass correct data to condition/expression statements
  - [ ] Attributes work on all possible screen sizes
- [ ] Object Manipulation
  - [ ] Moving objects/groups is reliable
  - [ ] Rotating objects/groups is reliable
  - [ ] Changing Z of objects/groups is reliable
  - [ ] Works without hiccups on multiplayer environment
- [ ] Documentation is up to date and understandable
- [ ] Tidy up old functions
- [ ] Remove/disable debug code
