### ISSUE TITLE
Marker TODO List

### ISSUE THREAD

**Issue by jameslkingsley** [marseditor/mars#57]
- [ ] On confirm, create marker
- [ ] Show to X side(s) option
- [ ] Ability to select marker in 2D/3D space
- [ ] Right-click marker for context options
